#+ endpoint: https://jpsearch.go.jp/rdf/sparql/
#+ summary: 古書・古文書の検索
#+ description: ジャパンサーチから古書・古文書タイプの資料を検索
#+ pagination: 20
#+ tags:
#+   - 古典資料

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX type: <https://jpsearch.go.jp/term/type/>

SELECT ?url WHERE {
  ?url rdf:type type:古書・古文書.
} LIMIT ?_limit
